### ISSUE TITLE
Thoughts on the top of the page

### ISSUE THREAD

**Issue by g-re-g** [leptos-rs/leptos-website#14]
Just some thoughts I had about the top of the page:
<img width="1314" alt="Screenshot 2023-07-16 at 6 58 43 PM" src="https://github.com/leptos-rs/leptos-website/assets/123515925/f81ab5a8-cb64-40ca-ad1e-2751f77770a4">

* `Home` is the only internal link on the page so you can never get back home from anywhere else with that nav bar and no other links will ever be highlighted. Maybe remove it?
* The `Docs` link takes you to the Book. My intuition was that `Docs` would take me to the `docs.rs` docs. Maybe change it to `Book`?
* The `API` link takes you to the docs.rs docs. There's nothing wrong with that per-se, but maybe it would be better named `Docs`?
* Next to the `Video` link is a `Documentation` link. This link also takes you too the Book. There's already a link to the Book a couple inches away, it also throws off my intuition for the same reason as the `Docs` link above.
* Rather than linking to the video maybe embed it?

Happy to implement any of this, or close the issue if its WAI. Whatever works for folks!

**Comment by stappersg** [comment]
> Happy to implement any of this

_Patches welcomes_         `-- Captain Obvious`
