### ISSUE TITLE
Counter and Save to Database examples don't work on mobile

### ISSUE THREAD

**Issue by SleeplessOne1917** [leptos-rs/leptos-website#21]
When viewing leptos.dev on Firefox Android, clicking the counter button does not increase the count, and the form for adding cookies to the database will not submit. I could still enter text in the input boxes though.

**Comment by benwis** [comment]
I'm definitely open to suggestions and especially PRs on how to fix it, but since Firefox is such a tiny slice of the market I'm not sure what to do about it

**Comment by SleeplessOne1917** [comment]
It's worth checking if this problem affects other mobile browsers at least.

**Comment by SleeplessOne1917** [comment]
I just tested on my android with a chromium based browser and had the same issue.

**Comment by benwis** [comment]
I've got reports of it working in browsers on Android 13 and 14. What version of Android and device are you using?

**Comment by SleeplessOne1917** [comment]
Android 13. It may be the choice of browsers I used. The chromium browser I tested with was bromite.

**Comment by benwis** [comment]
The advice I received is that a lot either don't support webassembly or don't enable it, so I'd check that out.

**Comment by SleeplessOne1917** [comment]
I enabled `javascript.options.wasm` in my about:config and the site worked. Odd that my browser didn't have that enabled by default, but it resolves the issue.
